### ISSUE TITLE
Sending a message might throw a TransferException

### ISSUE THREAD

**Issue by TFarla** [endroid/CmSms#1]
It seems that there is no error handling for [the exceptions that Guzzle](http://docs.guzzlephp.org/en/latest/quickstart.html#exceptions) may throw.

```php
public function sendMessages(array $messages, array $options = [])
{
    …
    $client = new GuzzleClient();
    $adapter = new GuzzleAdapter($client);
    $request = new Request('POST', $this->baseUrl, ['Content-Type' => 'application/json'], json_encode($json));
    $response = $adapter->sendRequest($request);
    …
}
```

It might be useful for the consumer of this bundle to not have to worry about those.
A possible solution is to throw a generic error that the user can catch.

What do you think?

**Comment by endroid** [comment]
Hi @TFarla, fair point. I agree a generic exception would be a more future proof and user friendly. I'll let you know when it is added.

**Comment by endroid** [comment]
Exceptions that occur when performing the request are now handled. As not only Guzzle exceptions occur (there was a use case where I received a Http\Client\Exception\HttpException) I catch every possible exception to make sure everything results in a RequestException.
