### ISSUE TITLE
Composer dependency ramsey/uuid

### ISSUE THREAD

**Issue by dorxy** [endroid/CmSms#2]
Message.php uses Ramsey\Uuid\Uuid which is not present in the dependencies in composer.json

**Comment by endroid** [comment]
Hi @dorxy you're right. I will add the dependency as soon as I get home from my vacation. Please add it to your own composer.json for now or if you can create a PR I will merge it from here. Thank you.

**Comment by dorxy** [comment]
No problem, I will create a PR tonight, have a nice carnavals holiday ;)

**Comment by endroid** [comment]
It's not a carnavals holiday, I'm in Malaysia but thanks anyway ;) When I get home I will also complete the status reports webhook and status dashboard so you can easily monitor the state of sent messages if you use Symfony.

**Comment by dorxy** [comment]
Seems more fun anyways! Unfortunately I'm not using Symfony yet, still on CakePHP so right now I'm only good for testing for stand-alone usage of the lib ;) very happy with it so far!

**Comment by endroid** [comment]
Hi @dorxy the dependency has been added.
